### ISSUE TITLE
installation problem??

### ISSUE THREAD

**Issue by Xtremely-Doped-Punk** [JuliaApproximation/RatFun.jl#5]
![image](https://user-images.githubusercontent.com/62172946/90770233-17b56580-e30f-11ea-88a9-23a79309df02.png)

**Comment by dlfivefifty** [comment]
This package hasn't been updated yet for Julia v1.0 so still has a REQUIRE file. Do you need it for something?

**Comment by Xtremely-Doped-Punk** [comment]
ohh i see thanks for the support. i am actually working with signal computation on julia and i might need it for some purposes. Do u know any other way too add this package to terminal.

**Comment by dlfivefifty** [comment]
you can `git clone` the package and add a Project.toml

**Comment by Xtremely-Doped-Punk** [comment]
pls do explain how to generate new project because i already tried but i was not able to add the project.toml to active packages even after doing activate command of Pkg in julia.

**Comment by Xtremely-Doped-Punk** [comment]
Is there any way that sub directory could be specified and i could add this package to my terminal according my error message up.

**Comment by dlfivefifty** [comment]
Use just use `] dev path/to/RatFun.jl` in Julia

**Comment by Xtremely-Doped-Punk** [comment]
thnks
